services:
  - type: web
    name: backend-uefbcs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.17.1
      - key: PORT
        value: 10000
